### ISSUE TITLE
Switch --ignore-invariant-violations doesn't work in daemon-mode.

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1128]
Using `Ampersand-v4.1.0.1 [master:80d49b70c]`, I expect `ampersand daemon --ignore-invariant-violations` to ignore invariant violations, as specified by `ampersand daemon --help`. 

However, when I run the command on some scripts, I get the following output, which clearly demonstrates that this is not the case.:

![image](https://user-images.githubusercontent.com/8522589/102982539-f954b600-450a-11eb-8f49-b03b3553af1c.png)

**Comment by hanjoosten** [comment]
This used to be the case, but it was solved some time ago (See https://github.com/AmpersandTarski/Ampersand/issues/1063).

**Comment by RieksJ** [comment]
Maybe the solution want good. Anyway, it is currently not solved yet/again.

**Comment by RieksJ** [comment]
As you can see by the screen dump.

**Comment by RieksJ** [comment]
If you think it is solved pkease tell me which switches i should use to only see errors and ignore violations

**Comment by hanjoosten** [comment]
`ampersand daemon --ignore-invariant-violations` 
This works for me, and I've tried it with the exact same version as you used.

**Comment by RieksJ** [comment]
Ok. That's really surprising! I think we should set up a Teams session or so to figure this out. I've sent you an invite.

**Comment by hanjoosten** [comment]
Did some archeology ;) We are both correct: It was solved with commit https://github.com/AmpersandTarski/Ampersand/commit/1d0d8dd64ffaf8368c81f7d565089234c889d8b8 , which made in into master at first in [release v4.1.1](https://github.com/AmpersandTarski/Ampersand/releases/tag/Ampersand-v4.1.1). 
You were using the last version that contained this bug, and apparently last week I fooled myself somehow using another version of ampersand than I thought I was using.
