### ISSUE TITLE
Internal error 500 when using underscore in a target conceptname 

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/Ampersand#459]
The script below results in an internal 500 error when opening the interface. 
The error message states that a concept is not defined. The target conceptname of the relation has two underscores i.s.o. one underscore.
(this is an updated version of this comment as the code was not complete the first time)

CONTEXT TestUnderscore
IN ENGLISH

CONCEPT Boom_tak "A concept with an underscore in it's name"

RELATION blad[Boom_tak*Boom_tak] [ASY]

POPULATION Boom_tak CONTAINS
[ "Boom 1" , "Boom 2"   ]

INTERFACE "Testen": V[SESSION*Boom_tak]
BOX
	[
		"Boom": I[Boom_tak]
         ,      "relatie met": blad
	]

ENDCONTEXT

**Comment by Michiel-s** [comment]
@EstherHageraats I can't reproduce this bug. Could you provide the ampersand version or commit you are using to build and the detailed error message. You can see this by clicking on the error.

**Comment by EstherHageraats** [comment]
@Michiel-s I attached two screenshots that will show what you asked for.
I use Ampersand v3.5.0[master:bf6e4b7], build time 28-Apr-16 10:06:21
![schermafdruk 2016-06-10 08 51 00](https://cloud.githubusercontent.com/assets/18698059/15956456/f0836928-2ee8-11e6-8525-fddc9054d060.png)
![schermafdruk 2016-06-10 08 51 31](https://cloud.githubusercontent.com/assets/18698059/15956459/f9bfe9bc-2ee8-11e6-8481-0b417236f4f8.png)

**Comment by Michiel-s** [comment]
Thx for your quick reply, but I'm sorry. When I generate a prototype of your script above with the Ampersand version you mention, I don't get this error.

I see however a difference in the user interface (from the screenshot) and the script you posted. The "Relatie met" sub interface is not mentioned. For me to debug this any further, please:
- Provide the actual script you are using to generate your prototype
- Email me the following files:
 - concepts.json (generated to ..pathtoapp/generics/concepts.json)
 - debug.log (from ..pathtoapp/logs/debug.log) after the error has occurred.

Happy to help you further with this issue by the way.

**Comment by EstherHageraats** [comment]
Oeps, the relation is not in that file. The problem occurs with the relation, the target cannot be found. Sorry. Here are the files you requested, plus relations.json.
[voor issue459.zip](https://github.com/AmpersandTarski/Ampersand/files/308704/voor.issue459.zip)

**Comment by Michiel-s** [comment]
Hi @EstherHageraats, I'm really sorry but I can't reproduce the error. Even not with the source files you provided. I can't find the error in the log file either. Could you just try again to build the prototype from a clean slate, i.e.:
* remove database
* remove folder from htdocs

**Comment by EstherHageraats** [comment]
Hi @Michiel-s and any that has Windows 10,
I removed the folder from htdocs and created a new prototype. 
I have reinstalled the database (other prototypes have been in there before).
Still same error.
With phpmyadmin I had a look at the database and the tables are created correctly. And as you don't get this message, maybe the problem is with the browser. So I deleted all history, but no changes.
I use Chrome, so next I tried Firefox: same error as soon as I opened the interface. 
This problem occured before in a script and that's why I made this test script. So I don't think making a new test script is useful. 
It's reproducable on my computer, not on yours. I am using Windows10, could that be the cause? Can anyone try to reproduce this on W10? 
For convenience I have updated my first comment so that the code is exactly as mine.

**Comment by Michiel-s** [comment]
Shall we have a look together via Skype? my skypeid: michielstornebrink@gmail.com

**Comment by EstherHageraats** [comment]
Prima, ik bel je via skype over 10 minuten
Esther

Verstuurd vanaf mijn iPhone

**Comment by Michiel-s** [comment]
We've identified the issue. It has to do with the escaping of special characters in concept names. We use a library for this which transform special characters in unicode pre- and postfixed by an underscore. The underscore itself gets prefixed by an underscore.

@hanjoosten and I discussed the solution and it involves some minor changes in the generated json files.
- [ ] in concepts.json the `name` attribute must be replaced by two new attributes: `id` and `label`. The first one must be the escaped identifier, the second one the name as specified in &-script.
- [ ] in concepts.json the list of `specializations` and `generalizations` must contains references to the concept by its escaped id
- [ ] in interfaces.json the `tgtConcept` and `srcConcept` attributes must be changed to `tgtConceptId` and `srcConceptId` and contain references to the concept by its escaped id
- [ ] in relations.json the `tgtConcept` and `srcConcept` attributes must be changed to `tgtConceptId` and `srcConceptId` and contain references to the concept by its escaped id
- [ ] in rules.json the `tgtConcept` and `srcConcept` attributes must be changed to `tgtConceptId` and `srcConceptId` and contain references to the concept by its escaped id
- [ ] in views.json the `concept` attribute must be changed to `conceptId` and contain references to the concept by its escaped id

This requires changes to both haskell part ( @hanjoosten will do that) and prototype back end ( I will do that).

**Comment by stefjoosten** [comment]
Sounds thorough. Good work! I'm happy about that because many more students would have run in the same error.
@EstherHageraats, has this issue ben resolved now? If yes, can you close this comment? If not, can you state what more is needed? Thanks.

**Comment by hanjoosten** [comment]
I still think that @Michiel-s has to do his thing on this issue. I do not think it is resolved yet. Is it?

**Comment by EstherHageraats** [comment]
Sorry guys, not fixed yet in v3.6.0
Enclosed the screenshot of the error and testen.js
[Archief.zip](https://github.com/AmpersandTarski/Ampersand/files/360924/Archief.zip)

If you need anything else, let me know.

**Comment by stefjoosten** [comment]
OK

Stef Joosten

M +31 (0)6 51348895
skype: stef.joosten




-----Oorspronkelijk bericht-----
Van: Esther Hageraats [mailto:notifications@github.com]
Verzonden: woensdag 13 juli 2016 9:44
Aan: Joosten, Stef
Onderwerp: Re: [AmpersandTarski/Ampersand] Internal error 500 when using underscore in a target conceptname (#459)

Sorry guys, not fixed yet in v3.6.0
Enclosed the screenshot of the error and testen.js Archief.zip<https://github.com/AmpersandTarski/Ampersand/files/360924/Archief.zip>

If you need anything else, let me know.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/AmpersandTarski/Ampersand/issues/459#issuecomment-232280452>, or mute the thread<https://github.com/notifications/unsubscribe/AAQ1OO7Bn4me9R0jQPTqYuwb8MwCtT2lks5qVJcagaJpZM4Iwvgx>.

________________________________
Deze e-mail is uitsluitend bestemd voor de geadresseerde(n). Verstrekking aan en gebruik door anderen is niet toegestaan. Open Universiteit sluit iedere aansprakelijkheid uit die voortvloeit uit elektronische verzending. Aan de inhoud van deze e-mail en/of eventueel toegevoegde bijlagen kunnen geen rechten worden ontleend.

This e-mail is intended exclusively for the addressee(s), and may not be passed on to, or made available for use by any person other than the addressee(s). Open Universiteit rules out any and every liability resulting from any electronic transmission. No rights may be derived from the contents of this message.

Disclaimer
Dit bericht met eventuele bijlagen is vertrouwelijk en uitsluitend bestemd voor de geadresseerde. Indien u niet de bedoelde ontvanger bent, wordt u verzocht de afzender te waarschuwen en dit bericht met eventuele bijlagen direct te verwijderen en/of te vernietigen. Het is niet toegestaan dit bericht en eventuele bijlagen te vermenigvuldigen, door te sturen, openbaar te maken, op te slaan of op andere wijze te gebruiken. Ordina N.V. en/of haar groepsmaatschappijen accepteren geen verantwoordelijkheid of aansprakelijkheid voor schade die voortvloeit uit de inhoud en/of de verzending van dit bericht.

This e-mail and any attachments are confidential and are solely intended for the addressee. If you are not the intended recipient, please notify the sender and delete and/or destroy this message and any attachments immediately. It is prohibited to copy, to distribute, to disclose or to use this e-mail and any attachments in any other way. Ordina N.V. and/or its group companies do not accept any responsibility nor liability for any damage resulting from the content of and/or the transmission of this message.
